---
version: "3.3"
services:    
  data_collector:
    build: .
    image: python_requests:1.0
    hostname: ${COMPOSE_PROJECT_NAME}
    container_name: ${COMPOSE_PROJECT_NAME}
    read_only: true
    volumes:
      - ./code:/usr/app/code/:ro
      - ./input:/usr/app/input:ro
      - ./output:/usr/app/output:rw
    entrypoint: /bin/bash /usr/app/code/entrypoint.sh
    security_opt:
      - no-new-privileges:true