---
version: "3.3"
services:    
  data_collector:
    build: .
    image: netappcollector:1.0
    hostname: netappcollector
    container_name: netappcollector
    read_only: true
    volumes:
      - ./code:/usr/app/code/:ro
      - ./input:/usr/app/input:ro
      - ./output:/usr/app/output:rw
    entrypoint: /bin/bash /usr/app/code/entrypoint.sh
    security_opt:
      - no-new-privileges:true